c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.10.* *_cpython
- 3.9.* *_cpython
- 3.8.* *_cpython
target_platform:
- linux-armv7l
zlib:
- '1.2'
